[workspace]
members = [
    "p0001_two_sum",
	"p0004_median_of_two_sorted_arrays",
	"p0011_container_with_most_water",
	"p0015_three_sum",
	"p0026_remove_duplicates_from_sorted_array",
	"p0033_search_in_rotated_sorted_array",
]
